export const CHANGE_THEME_START = 'CHANGE_THEME_START';
export const CHANGE_THEME_SUCCESS = 'CHANGE_THEME_SUCCESS';
export const CHANGE_THEME_FAILED = 'CHANGE_THEME_FAILED';

export const CHANGE_MODE_START = 'CHANGE_MODE_START';
export const CHANGE_MODE_SUCCESS = 'CHANGE_MODE_SUCCESS';
export const CHANGE_MODE_FAILED = 'CHANGE_MODE_FAILED';

export const CHANGE_ONBOARDING_SHOW = 'CHANGE_ONBOARDING_SHOW';

export const CHANGE_NOTIFICATION_STATE_START =
  'CHANGE_NOTIFICATION_STATE_START';
export const CHANGE_NOTIFICATION_STATE_SUCCESS =
  'CHANGE_NOTIFICATION_STATE_SUCCESS';
export const CHANGE_NOTIFICATION_STATE_FAILED =
  'CHANGE_NOTIFICATION_STATE_FAILED';

export const CHANGE_REMINDER_TIME = 'CHANGE_REMINDER_TIME';

export const CHANGE_LANGUAGE_START = 'CHANGE_LANGUAGE_START';
export const CHANGE_LANGUAGE_SUCCESS = 'CHANGE_LANGUAGE_SUCCESS';
export const CHANGE_LANGUAGE_FAILED = 'CHANGE_LANGUAGE_FAILED';

export const GET_VERSES_START = 'GET_VERSES_START';
export const GET_VERSES_SUCCESS = 'GET_VERSES_SUCCESS';
export const GET_VERSES_FAILED = 'GET_VERSES_FAILED';

export const ADD_VERSE_TO_FAV_START = 'ADD_VERSE_TO_FAV_START';
export const ADD_VERSE_TO_FAV_SUCCESS = 'ADD_VERSE_TO_FAV_SUCCESS';
export const ADD_VERSE_TO_FAV_FAILED = 'ADD_VERSE_TO_FAV_FAILED';

export const REMOVE_VERSE_TO_FAV_START = 'REMOVE_VERSE_TO_FAV_START';
export const REMOVE_VERSE_TO_FAV_SUCCESS = 'REMOVE_VERSE_TO_FAV_SUCCESS';
export const REMOVE_VERSE_TO_FAV_FAILED = 'REMOVE_VERSE_TO_FAV_FAILED';
